medical_transformation:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: medical_warehouse
      schema: staging
      threads: 1
  target: dev
